### PR TITLE
ui/chore: Update go.mod and go.sum

### PR DESCRIPTION
**Pull request by simar7**
Fix a build time issue that occurs while building the UI image.

### CODE REVIEW

**Comment by AndreyLevchenko** [comment]
Hi @simar7 
Could you give us more details about issue you are trying to fix?

Thanks

**Comment by simar7** [comment]
> Hi @simar7 Could you give us more details about issue you are trying to fix?
> 
> Thanks

hi @AndreyLevchenko nice to meet you. See details as below.


```
➜  postee git:(main) ✗ make docker-ui
Building image Dockerfile.ui....
docker build --no-cache -t aquasec/postee-ui:latest -f Dockerfile.ui .
[+] Building 43.7s (23/32)                                                                                                                                                                                            
 => [internal] load build definition from Dockerfile.ui                                                                                                                                                          0.0s
 => => transferring dockerfile: 767B                                                                                                                                                                             0.0s
 => [internal] load .dockerignore                                                                                                                                                                                0.0s
 => => transferring context: 2B                                                                                                                                                                                  0.0s
 => [internal] load metadata for docker.io/library/alpine:3.15                                                                                                                                                   1.5s
 => [internal] load metadata for docker.io/library/node:alpine3.15                                                                                                                                               2.1s
 => [internal] load metadata for docker.io/library/golang:1.16-alpine                                                                                                                                            2.0s
 => [auth] library/golang:pull token for registry-1.docker.io                                                                                                                                                    0.0s
 => [auth] library/node:pull token for registry-1.docker.io                                                                                                                                                      0.0s
 => [auth] library/alpine:pull token for registry-1.docker.io                                                                                                                                                    0.0s
 => CACHED [stage-2  1/14] FROM docker.io/library/alpine:3.15@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300                                                                            0.0s
 => [internal] load build context                                                                                                                                                                               23.9s
 => => transferring context: 214.04MB                                                                                                                                                                           23.7s
 => [vuebuilder 1/5] FROM docker.io/library/node:alpine3.15@sha256:7ef8e673a9ea7b1dfaae292bf8faf549bb81ba60f68087454cef143698bdf2c4                                                                             24.7s
 => => resolve docker.io/library/node:alpine3.15@sha256:7ef8e673a9ea7b1dfaae292bf8faf549bb81ba60f68087454cef143698bdf2c4                                                                                         0.0s
 => => sha256:7ef8e673a9ea7b1dfaae292bf8faf549bb81ba60f68087454cef143698bdf2c4 1.43kB / 1.43kB                                                                                                                   0.0s
 => => sha256:1c34d5df5dbf743fc93624531e0e443e8c5c69e930cebbb9a46d4867ca24ee3e 1.16kB / 1.16kB                                                                                                                   0.0s
 => => sha256:d0ea4d2aa898ffb357db403651e7bbd6e1d27a589f14a022cbf401ecf622251a 6.53kB / 6.53kB                                                                                                                   0.0s
 => => sha256:041fc259677c3ff8bde53adb15663a1190ef9689bd7ba47cbe1ad0c6439cd397 46.07MB / 46.07MB                                                                                                                 8.5s
 => => sha256:3635214f04a23378fe8a876564c367a0590c760ef8aacad2cacc6670050f5321 2.35MB / 2.35MB                                                                                                                   1.5s
 => => sha256:023c6dafc860129394e270d20ebe62ac3b9b8ee6680dd4cc7cd5de3ea289f79a 451B / 451B                                                                                                                       1.6s
 => => extracting sha256:041fc259677c3ff8bde53adb15663a1190ef9689bd7ba47cbe1ad0c6439cd397                                                                                                                       14.7s
 => => extracting sha256:3635214f04a23378fe8a876564c367a0590c760ef8aacad2cacc6670050f5321                                                                                                                        0.5s
 => => extracting sha256:023c6dafc860129394e270d20ebe62ac3b9b8ee6680dd4cc7cd5de3ea289f79a                                                                                                                        0.0s
 => [gobuilder 1/4] FROM docker.io/library/golang:1.16-alpine@sha256:c4b36cff558405c8368be606325261a21a9a3ae9f79dc1bd3fff9f831a0411f2                                                                           29.5s
 => => resolve docker.io/library/golang:1.16-alpine@sha256:c4b36cff558405c8368be606325261a21a9a3ae9f79dc1bd3fff9f831a0411f2                                                                                      0.0s
 => => sha256:666ba61612fd7c93393f9a5bc1751d8a9929e32d51501dba691da9e8232bc87b 282.16kB / 282.16kB                                                                                                               0.2s
 => => sha256:8ed8ca4862056a130f714accb3538decfa0663fec84e635d8b5a0a3305353dee 155B / 155B                                                                                                                       0.2s
 => => sha256:fa6e261410ce0cebd518eb5ee56b9bb56fa66883992dc54ab7bd25afdca2b521 105.85MB / 105.85MB                                                                                                              14.6s
 => => sha256:c4b36cff558405c8368be606325261a21a9a3ae9f79dc1bd3fff9f831a0411f2 1.65kB / 1.65kB                                                                                                                   0.0s
 => => sha256:802b7b395fac3d9b0ed552be257a3f19739486f6e712b7f5276f76214ad1efa1 1.36kB / 1.36kB                                                                                                                   0.0s
 => => sha256:4bcb0d501de3d5c9d95c65a8ef94ef2d169244bf06970413780748ac6fc7536c 5.20kB / 5.20kB                                                                                                                   0.0s
 => => extracting sha256:666ba61612fd7c93393f9a5bc1751d8a9929e32d51501dba691da9e8232bc87b                                                                                                                        0.9s
 => => sha256:033ff68f5bd26b7f1a7567e74101649886332f6bffed2928025b2dc88a49a909 155B / 155B                                                                                                                       0.6s
 => => extracting sha256:8ed8ca4862056a130f714accb3538decfa0663fec84e635d8b5a0a3305353dee                                                                                                                        0.0s
 => => extracting sha256:fa6e261410ce0cebd518eb5ee56b9bb56fa66883992dc54ab7bd25afdca2b521                                                                                                                       13.9s
 => => extracting sha256:033ff68f5bd26b7f1a7567e74101649886332f6bffed2928025b2dc88a49a909                                                                                                                        0.0s
 => [stage-2  2/14] RUN mkdir /uiserver                                                                                                                                                                          1.2s
 => [stage-2  3/14] RUN mkdir /uiserver/www                                                                                                                                                                      1.2s
 => [stage-2  4/14] RUN mkdir /server                                                                                                                                                                            1.5s
 => [stage-2  5/14] RUN mkdir /server/database                                                                                                                                                                   1.5s
 => [stage-2  6/14] RUN mkdir /config                                                                                                                                                                            1.8s
 => [vuebuilder 2/5] COPY ./ui/frontend /frontend                                                                                                                                                               13.7s
 => [gobuilder 2/4] COPY . /server                                                                                                                                                                               9.4s
 => [gobuilder 3/4] WORKDIR /server/ui/backend                                                                                                                                                                   0.0s
 => [vuebuilder 3/5] WORKDIR /frontend                                                                                                                                                                           0.0s
 => ERROR [gobuilder 4/4] RUN go build -o posteeui                                                                                                                                                               2.5s
 => CANCELED [vuebuilder 4/5] RUN yarn install                                                                                                                                                                   2.6s
------
 > [gobuilder 4/4] RUN go build -o posteeui:
#19 2.413 go: github.com/aquasecurity/postee@v1.1.5-0.20211210093651-b669cce16033 requires
#19 2.413       github.com/open-policy-agent/opa@v0.35.0 requires
#19 2.413       github.com/dgraph-io/badger/v3@v3.2103.2 requires
#19 2.413       golang.org/x/net@v0.0.0-20201021035429-f5854403a974 requires
#19 2.413       golang.org/x/crypto@v0.0.0-20200622213623-75b288015ac9: missing go.sum entry; to add it:
#19 2.413       go mod download golang.org/x/crypto
------
executor failed running [/bin/sh -c go build -o posteeui]: exit code: 1
make: *** [docker-ui] Error 1
```

**Comment by simar7** [comment]
The go pkg dependency files just needs to have an entry for the library. Although as seen in the Trivy code scanning check we need to use a later version than what `go mod tidy` recommends by default. I can update that in.

**Comment by AndreyLevchenko** [comment]
Hi @simar7 
could we have 
```
replace golang.org/x/crypto v0.0.0-20200622213623-75b288015ac9 => golang.org/x/crypto v0.0.0-20201216223049-8b5274cf687f
``` 
in both go.mod files?
I afraid that `go.sum` can be eventually replaced by `go mod tidy`

**Comment by AndreyLevchenko** [comment]
Hi @simar7 
I've merged #234 which can resolve issue. Please test if it resolves issue for you and let me know results

Thanks
Andrey

**Comment by simar7** [comment]
> Hi @simar7 
> 
> I've merged #234 which can resolve issue. Please test if it resolves issue for you and let me know results
> 
> 
> 
> Thanks
> 
> Andrey

Awesome! Looks good. I'll close this then.

**Pull request closed without merging**
