### PR TITLE
Feat: added kubernete secrets

### PR DESCRIPTION
**Pull request by DmitriyLewen**
added kubernetes deployment file using secrets
Issue #120

### CODE REVIEW

**Comment by AndreyLevchenko** [comment]
@krol3 
should we use it as default example?

**Comment by krol3** [comment]
To create the secret we dont need to update the yaml:

```
kubectl create secret generic db-user-pass \
  --from-literal=username=devuser \
  --from-literal=password='xxxx'
```

The username in the email could be different from the Service now, and in the other outputs samples.

**Review by krol3 — COMMENTED** [review]
By now, we try to keep simple with a quick installation from yaml. This effort to create configmaps and secrets will put in the helm chart. Please hold this PR to the helm charts.

**Comment by AndreyLevchenko** [comment]
closing in favour of #227

**Pull request closed without merging**
