### PR TITLE
Feat(helm): extra volumes and volume mounts

### PR DESCRIPTION
**Pull request by fbuchmeier-abi**
This change introduces the possibility to mount custom volumes (secrets, configmaps, pvcs) into the postee pod. This allows different use cases like deploying your exec action scripts as configmaps, adding sensitive data as secrets or injecting a set of already prepared tools into the container.

The reasoning behind this is to separate the deployment lifecycle of credentials and code from postee.
A full example would look like this:

*Helm Values*
```
# Mount additional volumes into the postee container, one for secrets, one for code to run with the exec action
extraVolumes:
  - name: custom-secrets
    secret:
      defaultMode: 0420
      secretName: custom-secrets
  - name: custom-code
    configMap:
      defaultMode: 0755
      name: custom-code

extraVolumeMounts:
  - name: my-secrets
    mountPath: /actions/exec/custom/secrets
    readOnly: true
  - name: custom-code
    mountPath: /actions/exec/custom/code
    readOnly: true
```

*Postee Config*
```
routes:
  - name: custom
    input: input.type = "SCANNING_COMPLETED"
    actions: [custom]
    template: raw-json

templates:
  - name: raw-json
    rego-package: postee.rawmessage.json

actions:
  - name: custom
    type: exec
    enable: true
    exec-script: |-
      #!/bin/sh
      source /actions/exec/custom/secrets/*
      /actions/exec/custom/code/entrypoint.sh
```

*custom-secrets*
```
apiVersion: v1
kind: Secret
metadata:
  name: custom-secrets
  namespace: postee
stringData:
  env: |-
    export MY_USER=bob
    export MY_PASSWORD=kraut
type: Opaque
```

*custom-code*
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-code
  namespace: postee
data:
  entrypoint.sh: |-
    #!/bin/sh
    # Get the directly this script is located at
    SCRIPTDIR=$( dirname -- "$( readlink -f -- "$0"; )"; )
    # Print out data from 'custom-secrets'
    echo "Username: ${MY_USER}"
    echo "Password: ${MY_PASSWORD}"
    # Load another helper script
    source "${SCRIPTDIR}/helper.sh"
    # Execute a function from this script
    hello_world
  helper.sh: |-
    #!/bin/sh
    function hello_world() {
      echo "Hello World!"
    }
```

### CODE REVIEW

**Comment by fbuchmeier-abi** [comment]
> [CLA assistant check](https://cla-assistant.io/aquasecurity/postee?pullRequest=506) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/postee?pullRequest=506) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/postee?pullRequest=506) it.

I'm currently clarifying this with my company if the CLA can be signed.

**Comment by smangels** [comment]
@fbuchmeier-abi, I have a signed CLA and am interested getting the same feature as well. Shall I file that one under my account?

**Review by smangels — COMMENTED** [review]
this is what we would need as well, so that we could provide more complex action scripts (type exec) and rego templates. through volume mounts

**Comment by fbuchmeier-abi** [comment]
> @fbuchmeier-abi, I have a signed CLA and am interested getting the same feature as well. Shall I file that one under my account?

Hi, that would be great, thanks. We had some trouble with the CLA so I was not yet able to sign it.

**Pull request closed without merging**
