### PR TITLE
fix(helm): update postee version

### PR DESCRIPTION
**Pull request by DmitriyLewen**
## Description
Helm uses old version of Postee. 
Update it.

### CODE REVIEW

**Comment by DmitriyLewen** [comment]
@simar7 can you take a look, please.

**Review by simar7 — APPROVED** [review]
lgtm

**Comment by simar7** [comment]
> @simar7 can you take a look, please.

Merged.

> 
> We also need to remember to update the `Aqua Chart Repository` after merging this PR.

Could you look into this?

**Comment by DmitriyLewen** [comment]
`helm repo` still doesn't contains `v2.13.0`:
```
➜  ~ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "aquasecurity" chart repository
Update Complete. ⎈Happy Helming!⎈
➜  ~ helm search repo aquasecurity -l | grep v2.1
aquasecurity/postee              	v2.12.0      	v2.12.0    	A Helm chart for Postee                           
aquasecurity/postee              	v2.11.2      	v2.11.2    	A Helm chart for Postee                           
aquasecurity/postee              	v2.11.1      	v2.11.1    	A Helm chart for Postee                           
aquasecurity/postee              	v2.11.0      	v2.11.0    	A Helm chart for Postee                           
aquasecurity/postee              	v2.10.2      	v2.10.2    	A Helm chart for Postee                           
aquasecurity/postee              	v2.1.0       	v2.1.0     	A Helm chart for Postee   
```

But `aquasecurity/helm-charts` contains `v2.13.0` release - https://github.com/aquasecurity/helm-charts/releases/tag/postee-v2.13.0.
I installed postee from release file:
```
➜  helm install app --create-namespace -n postee postee-v2.13.0.tgz 
...

➜  kubectl get pods -n postee -o jsonpath="{.items[*].spec.containers[*].image}"
aquasec/postee:2.12.0-amd64 aquasec/postee-ui:2.12.0-amd64% 
```
It works correctly.

If i understand correctly - we need to wait when `https://aquasecurity.github.io/helm-charts/` page will be updated (https://github.com/aquasecurity/helm-charts/actions/workflows/pages/pages-build-deployment)

**Comment by DmitriyLewen** [comment]
I can't find this information, because `helm-chart` doesn't use `.github` folder with workflow configs. 
I asked about this [here](https://github.com/aquasecurity/helm-charts/issues/6).

I'll write to you after answering or updating GH-pages.

**Comment by thiagolinhares** [comment]
helm repo still not updated. Any updates on this?

**Comment by DmitriyLewen** [comment]
hm... strange case.
Looks like [our action](https://github.com/aquasecurity/postee/actions/runs/5576434122/job/15099774958#step:11:13) didn't update [index.yaml](https://github.com/aquasecurity/helm-charts/blob/82e97c4c349fd71c9d7a81464c1da4d6e289e1ed/index.yaml#L305).

@simar7 Can we try to rerun `publish` action or will that not help?

**Comment by simar7** [comment]
> hm... strange case. Looks like [our action](https://github.com/aquasecurity/postee/actions/runs/5576434122/job/15099774958#step:11:13) didn't update [index.yaml](https://github.com/aquasecurity/helm-charts/blob/82e97c4c349fd71c9d7a81464c1da4d6e289e1ed/index.yaml#L305).
> 
> @simar7 Can we try to rerun `publish` action or will that not help?

I've released a new version, it should be available now

```shell

 helm search repo aquasecurity -l | grep v2.14
aquasecurity/postee                     v2.14.0         v2.14.0         A Helm chart for Postee 
```

**Pull request merged**
