### PR TITLE
feat(Helm): Provide sensitive values as secret

### PR DESCRIPTION
**Pull request by tibuntu**
Related to #479

A little bit of a lazy implementation but this way we could simply overwrite the whole content of the config file as a secret provided from another source (Hashicorp Vault + External Secrets Operator in our case)

Open for feedback of course but I am going to be on vacation for two weeks now.

Cheers!

### CODE REVIEW

**Comment by tibuntu** [comment]
Any chance of getting feedback soon? 🙂

**Comment by simar7** [comment]
thanks for the PR, @DmitriyLewen - could you take a look at this?

**Review by DmitriyLewen — APPROVED** [review]
LGTM. Thanks for your work!

**Comment by tibuntu** [comment]
@DmitriyLewen are you going to merge this soon?

**Comment by DmitriyLewen** [comment]
@simar7 i approved this PR. If you don't have any question - i think we can merge it.

**Pull request merged**
