### PR TITLE
helm - support for additional volumes

### PR DESCRIPTION
**Pull request by smangels**
- credits to @fbuchmaier-abi for his work
- posted as PR because of CLA issues for @fbuchmaier-abi
- closes #506

### CODE REVIEW

**Comment by smangels** [comment]
@simar7 , I've copied the code provided in #506 that have never been passed the CLA step, credits to @fbuchmaier

**Comment by smangels** [comment]
this way we could solve the issue with easily mounting action scripts and rego templates into the postee POD.

**Comment by simar7** [comment]
thanks for the PR @smangels - @afdesk or @nikpivkin can you review this?

**Comment by nikpivkin** [comment]
tested, looks good 
/cc @afdesk

**Review by simar7 — APPROVED** [review]

**Comment by smangels** [comment]
Hi everyone, thanks for merging this PR. I'll wait until a new official helm package has been released.

**Pull request merged**
