### PR TITLE
feat(actions): Add output serialization option per route.

### PR DESCRIPTION
**Pull request by simar7**
This will help user chain different actions use output as input to the next.

Signed-off-by: Simar <simar@linux.com>

### CODE REVIEW

**Comment by AndreyLevchenko** [comment]
@simar7 
Looks good but seems tests are failed

**Comment by simar7** [comment]
> @simar7
> Looks good but seems tests are failed

Yes - fixed the tests here https://github.com/aquasecurity/postee/pull/302/commits/89fd1436ae93d210121524c62c7098a90a7c9ac9

**Review by AndreyLevchenko — APPROVED** [review]

**Comment by itaysk** [comment]
can we please document this feature?

**Comment by simar7** [comment]
> can we please document this feature?

Thanks, Will do so.

**Pull request merged**
