### PR TITLE
feat(servicenow): add templates

### PR DESCRIPTION
**Pull request by DmitriyLewen**
## Description
Add templates for some aqua reports:
- [x] Image report
- [x] VM report
- [x] function report
- [x] Incident report
- [x] insight report

### CODE REVIEW

**Comment by simar7** [comment]
thanks @DmitriyLewen - looks good, can we add some template functional tests (either rego or go is fine) to make sure that the templates are working as intended? 

ideally such a test would mean passing in data as input and asserting the output after template renders it.

**Comment by DmitriyLewen** [comment]
Hm... i think is possible. 
@simar7 I will try to make this soon.

**Comment by simar7** [comment]
any update on this @DmitriyLewen?

**Comment by DmitriyLewen** [comment]
Hello @simar7 
I'm currently busy with other important tasks. 

If users need these templates now - i think you can merge this PR. 
We tested these templates in `postee-for-enterprise` branch.(#487)

If you do - I'll just create new PR with tests when I have time for it.

**Review by simar7 — APPROVED** [review]

**Pull request merged**
