### PR TITLE
add maintenance notice

### PR DESCRIPTION
**Pull request by itaysk**

### CODE REVIEW

**Comment by rfletcher-duo** [comment]
Is there a link to more context anywhere? (Is there a recommended alternative?)

**Comment by rfletcher** [comment]
Is there somewhere users can get more context about this decision? And are there any recommended alternatives?

**Comment by itaysk** [comment]
Hi @rfletcher there's not alot to add, this message merely reflects reality, in which there are no engineering resources dedicated to this project. If it works for you, feel free to continue using it, but if you prefer to find another solution, there should be various other ways to integrate data across tools.

**Comment by rfletcher** [comment]
We weren't using it yet, but were planning to introduce Postee to our stack along side trivy-operator. I'll look for an alternative. Thanks for the reply.

**Pull request merged**
